<<<<<<< HEAD

import "./globals.css";
import style from "./styles/dashboards.scss";
import Header from "./components/header" 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";
import "./styles/style.scss";
import "./styles/responsive.scss";
import Header from "./components/header";
import Footer from "./components/footer";
export const metadata = {
  title: "AST UK",
  description: "",
>>>>>>> 9f7322267dc4f0f5eeff189603527f07cbc0ff55
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
<<<<<<< HEAD
        
        {children}
=======
          <Header />
        {children}
        <Footer />
>>>>>>> 9f7322267dc4f0f5eeff189603527f07cbc0ff55
      </body>
    </html>
  );
}
